from numpy import dtype

data_type = {'arp.opcode': dtype('float64'),
 'arp.hw.size': dtype('float64'),
 'icmp.checksum': dtype('float64'),
 'icmp.seq_le': dtype('float64'),
 'icmp.unused': dtype('float64'),
 'http.content_length': dtype('float64'),
 'http.request.method': dtype('O'),
 'http.referer': dtype('O'),
 'http.request.version': dtype('O'),
 'http.response': dtype('float64'),
 'http.tls_port': dtype('float64'),
 'tcp.ack': dtype('float64'),
 'tcp.ack_raw': dtype('float64'),
 'tcp.checksum': dtype('float64'),
 'tcp.connection.fin': dtype('float64'),
 'tcp.connection.rst': dtype('float64'),
 'tcp.connection.syn': dtype('float64'),
 'tcp.connection.synack': dtype('float64'),
 'tcp.flags': dtype('float64'),
 'tcp.flags.ack': dtype('float64'),
 'tcp.len': dtype('float64'),
 'tcp.seq': dtype('float64'),
 'udp.stream': dtype('float64'),
 'udp.time_delta': dtype('float64'),
 'dns.qry.name': dtype('float64'),
 'dns.qry.name.len': dtype('O'),
 'dns.qry.qu': dtype('float64'),
 'dns.qry.type': dtype('float64'),
 'dns.retransmission': dtype('float64'),
 'dns.retransmit_request': dtype('float64'),
 'dns.retransmit_request_in': dtype('float64'),
 'mqtt.conack.flags': dtype('O'),
 'mqtt.conflag.cleansess': dtype('float64'),
 'mqtt.conflags': dtype('float64'),
 'mqtt.hdrflags': dtype('float64'),
 'mqtt.len': dtype('float64'),
 'mqtt.msg_decoded_as': dtype('float64'),
 'mqtt.msgtype': dtype('float64'),
 'mqtt.proto_len': dtype('float64'),
 'mqtt.protoname': dtype('O'),
 'mqtt.topic': dtype('O'),
 'mqtt.topic_len': dtype('float64'),
 'mqtt.ver': dtype('float64'),
 'mbtcp.len': dtype('float64'),
 'mbtcp.trans_id': dtype('float64'),
 'mbtcp.unit_id': dtype('float64'),
 'Attack_label': dtype('int64'),
 'Attack_type': dtype('O')}


selected_features = ['icmp.checksum', 'icmp.seq_le', 'http.content_length', 'http.request.method', 'http.referer',
                    'http.request.version', 'http.response', 'tcp.ack', 'tcp.ack_raw', 'tcp.checksum', 'tcp.len', 'tcp.seq',
                    'tcp.connection.fin', 'tcp.connection.rst', 'tcp.connection.syn', 'tcp.connection.synack', 'tcp.flags', 'tcp.flags.ack',
                    'udp.stream', 'udp.time_delta', 'dns.qry.name', 'dns.qry.name.len', 'dns.qry.qu', 'dns.retransmission', 'dns.retransmit_request',
                    'mqtt.conack.flags', 'mqtt.conflag.cleansess', 'mqtt.conflags', 'mqtt.hdrflags', 'mqtt.len',
                    'mqtt.msgtype', 'mqtt.proto_len', 'mqtt.protoname', 'mqtt.topic', 'mqtt.topic_len', 'mqtt.ver']